"""Add Address, Cart, CartItem and Reports tables

Revision ID: 3f6e8514ccd3
Revises: 87ac581c2dd9
Create Date: 2025-11-04 23:42:48.147867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6e8514ccd3'
down_revision: Union[str, None] = '87ac581c2dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la dirección'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Usuario propietario (NULL para direcciones de listings sin usuario)'),
    sa.Column('street', sa.String(length=255), nullable=False, comment='Calle y número'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='Ciudad o municipio'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='Estado, provincia o región'),
    sa.Column('postal_code', sa.String(length=20), nullable=False, comment='Código postal'),
    sa.Column('country', sa.String(length=2), nullable=False, comment='Código de país ISO 3166-1 alpha-2 (ej: MX, US, CA)'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='Referencias adicionales, indicaciones de ubicación'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Indica si es la dirección predeterminada del usuario'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.CheckConstraint("country ~ '^[A-Z]{2}$'", name='ck_address_country_iso_format'),
    sa.CheckConstraint('length(postal_code) >= 4', name='ck_address_postal_code_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del carrito'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Usuario propietario del carrito (relación 1:1)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=True)
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del item del carrito'),
    sa.Column('cart_id', sa.Integer(), nullable=False, comment='Carrito al que pertenece este item'),
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Listing (producto/material) agregado al carrito'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Cantidad de unidades seleccionadas'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.CheckConstraint('quantity > 0', name='ck_cart_item_quantity_positive'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.cart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cart_item_id'),
    sa.UniqueConstraint('cart_id', 'listing_id', name='uq_cart_item_cart_listing')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index('ix_cart_items_cart_listing', 'cart_items', ['cart_id', 'listing_id'], unique=False)
    op.create_index(op.f('ix_cart_items_listing_id'), 'cart_items', ['listing_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del reporte'),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False, comment='Llave foránea a users (usuario que reporta)'),
    sa.Column('report_type', sa.Enum('LISTING', 'USER', 'ORDER', name='report_type_enum'), nullable=False, comment='Tipo de reporte: listing, user u order'),
    sa.Column('reported_listing_id', sa.Integer(), nullable=True, comment='Llave foránea a listings (si se reporta un listing)'),
    sa.Column('reported_user_id', sa.Integer(), nullable=True, comment='Llave foránea a users (si se reporta un usuario)'),
    sa.Column('reported_order_id', sa.Integer(), nullable=True, comment='Llave foránea a orders (si se reporta una orden)'),
    sa.Column('reason', sa.String(length=255), nullable=False, comment='Razón o motivo del reporte'),
    sa.Column('details', sa.Text(), nullable=True, comment='Detalles adicionales opcionales sobre el reporte'),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='moderation_status_enum'), server_default=sa.text("'PENDING'"), nullable=False, comment='Estado de moderación del reporte'),
    sa.Column('resolved_by_admin_id', sa.Integer(), nullable=True, comment='Llave foránea a users (admin que resolvió el reporte)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['reported_listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.add_column('listings', sa.Column('location_address_id', sa.Integer(), nullable=True, comment='ID de la dirección donde se encuentra el ítem físicamente'))
    op.create_foreign_key(None, 'listings', 'addresses', ['location_address_id'], ['address_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'location_address_id')
    op.drop_table('reports')
    op.drop_index(op.f('ix_cart_items_listing_id'), table_name='cart_items')
    op.drop_index('ix_cart_items_cart_listing', table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
